name: GET
on:
  schedule:
    - cron: '10 15 * * *'

jobs:
  fetch_source:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install envitonment
      run: |
        sudo apt-get -y update
        sudo apt-get -y install dos2unix libxml2-utils
    - name: Fetch source
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        TZ: "Asia/Tokyo"
      run: |
        ./crawler.sh
